# Generated by Django 5.1.2 on 2024-11-15 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membres', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membre',
            old_name='telephone',
            new_name='phone_number',
        ),
    ]
