# Generated by Django 5.1.2 on 2024-10-12 13:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0002_module_quizz'),
    ]

    operations = [
        migrations.RenameField(
            model_name='module',
            old_name='formation',
            new_name='module_formation',
        ),
        migrations.RenameField(
            model_name='quizz',
            old_name='choix_reponses',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='moduleformation',
            name='date_debut',
        ),
        migrations.RemoveField(
            model_name='moduleformation',
            name='date_fin',
        ),
        migrations.RemoveField(
            model_name='quizz',
            name='question',
        ),
        migrations.RemoveField(
            model_name='quizz',
            name='reponse_correcte',
        ),
        migrations.AddField(
            model_name='quizz',
            name='titre',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.TextField()),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formation.module')),
            ],
        ),
        migrations.CreateModel(
            name='Choix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.CharField(max_length=200)),
                ('est_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formation.question')),
            ],
        ),
    ]
